### ISSUE TITLE
Open Source Software Stack for 3G

### ISSUE THREAD

**Issue by serttasbugrahan** [garronej/gsm-modem-connection#6]
I am looking for open source software stack for 3G, like OpenAirInterface for 5G or Osmocom for 2G. (Osmocom has partial support for 3G)

Kindly asking you to forward me to the right source who may know.

Thank you for your time and kind attention.

Best Regards,

**Comment by garronej** [comment]
Hi @serttasbugrahan,  

Sorry, unfortunately I have no conexion in the buisness.  
I can however point you toward the tack that I build:  

https://github.com/garronej/chan-dongle-extended  
https://github.com/garronej/ts-gsm-modem  
https://github.com/garronej/ts-async-agi  
https://github.com/garronej/gsm-modem-connection  

https://garronej.github.io/chan-dongle-extended-pages/ would be the entry point.  

Best
